version: '3.8'

services:
  # setup nginx for reverse proxying
  msb-blog-sv:
    image: 13angs/msb-blog-sv:${msb_blog_sv_img_version}
    build: 
      context: ../../../../
      dockerfile: apps/blog-sv/Dockerfile
    container_name: msb-blog-sv
    restart: unless-stopped
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"