apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.name }}-secret
type: Opaque
data:
  root_password: {{ .Values.mongodb.secrets.rootPass | b64enc }}
  admin_password: {{ .Values.mongodb.secrets.rootPass | b64enc }} # password

--- 

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.mongodb.name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
  storageClassName: {{ .Values.mongodb.persistence.storageClassName }}

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.mongodb.name }}-pv
spec:
  capacity:
    storage: {{ .Values.mongodb.persistence.size }}
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.mongodb.persistence.storageClassName }}
  hostPath:
    path: {{ .Values.mongodb.persistence.hostPath.path }}

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.mongodb.name }}-configmap
data:
  db_server: {{ .Values.mongodb.name }}-srv
  db_root_user: root
  db_admin_user: admin
  db_url: "mongodb://root:password@mongodb-srv:27017"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.mongodb.name }}-depl
  labels:
    app: {{ .Values.mongodb.labels.app }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.mongodb.labels.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.mongodb.labels.app }}
    spec:
      containers:
        - name: mongodb-con
          image: {{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: db_root_user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: root_password
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
---

apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mongodb.name }}-srv
spec:
  selector:
    app: {{ .Values.mongodb.labels.app }}
  ports:
    - port: 27017
      name: mongodb-srv
      targetPort: 27017
      protocol: TCP
      nodePort: 30000
  type: NodePort




