apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-depl
  labels:
    app: mongo-db
spec:
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-db-con
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: "root"
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: "password"
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db-srv
spec:
  selector:
    app: mongo-db
  ports:
    - port: 27017
      name: mongo-db-srv
      targetPort: 27017
      protocol: TCP