apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-db-depl
  labels:
    app: mongo-db
spec:
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db
    spec:
      containers:
        - name: mongo-db-con
          image: mongo:latest
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-data
              mountPath: /data/db
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: db_root_user
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: root_password
      volumes:
      - name: mongodb-data
        persistentVolumeClaim:
          claimName: mongodb-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-db-srv
spec:
  selector:
    app: mongo-db
  ports:
    - port: 27017
      name: mongo-db-srv
      targetPort: 27017
      protocol: TCP
      nodePort: 30000
  type: NodePort