apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express-depl
  labels:
    app: mongodb-express
spec:
  selector:
    matchLabels:
      app: mongodb-express
  template:
    metadata:
      labels:
        app: mongodb-express
    spec:
      containers:
        - name: mongodb-express-con
          image: mongo-express:latest
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              valueFrom:
                configMapKeyRef: 
                  name: mongodb-configmap
                  key: db_root_user
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: root_password
            - name: ME_CONFIG_MONGODB_SERVER
              valueFrom:
                configMapKeyRef:
                  name: mongodb-configmap
                  key: db_server
            - name: ME_CONFIG_BASICAUTH_USERNAME
              valueFrom:
                configMapKeyRef: 
                    name: mongodb-configmap
                    key: db_admin_user
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              valueFrom:
                secretKeyRef:
                    name: mongodb-secret
                    key: root_password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-srv
spec:
  selector:
    app: mongodb-express
  ports:
    - port: 8081
      name: mongodb-express-srv
      targetPort: 8081
      protocol: TCP
      nodePort: 30001
  type: NodePort

    