apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express-depl
  labels:
    app: mongodb-express
spec:
  selector:
    matchLabels:
      app: mongodb-express
  template:
    metadata:
      labels:
        app: mongodb-express
    spec:
      containers:
        - name: mongodb-express-con
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: "root"
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: "password"
            - name: ME_CONFIG_MONGODB_URL
              value: "mongodb://root:password@mongo-db-srv:27017"
            - name: ME_CONFIG_BASICAUTH_USERNAME
              value: "admin"
            - name: ME_CONFIG_BASICAUTH_PASSWORD
              value: "P@ssw0rd"
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-srv
spec:
  selector:
    app: mongodb-express
  ports:
    - port: 8081
      name: mongodb-express-srv
      targetPort: 8081
      protocol: TCP
      nodePort: 30001
  type: NodePort

    